### ISSUE TITLE
Exception when using template

### ISSUE THREAD

**Issue by jhiemer** [pivotal-cf/docs-partners-template#6]
Hi,
I tried to use the template today, but I got the following error:

```bash
E, [2018-08-16T08:17:26.075840 #2238] ERROR -- : exception while processing events: Is a directory @ io_fread - /path/to/oss/docs-partners-template/docs-book/output/master_middleman/source/myservice Backtrace:

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util/binary.rb:70:in `read'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util/binary.rb:70:in `file_contents_include_binary_bytes?'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util/binary.rb:38:in `binary?'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/resource.rb:175:in `binary?'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/core_extensions/front_matter.rb:37:in `block in manipulate_resource_list'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/core_extensions/front_matter.rb:36:in `each'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/core_extensions/front_matter.rb:36:in `manipulate_resource_list'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:234:in `block (4 levels) in ensure_resource_list_updated!'

 -- /Library/Ruby/Gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:232:in `block (3 levels) in ensure_resource_list_updated!'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:231:in `block (2 levels) in ensure_resource_list_updated!'

 -- /Library/Ruby/Gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:224:in `block in ensure_resource_list_updated!'

 -- /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:221:in `ensure_resource_list_updated!'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/extensions/on_disk.rb:51:in `update_files'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sources.rb:366:in `block in run_callbacks'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sources.rb:359:in `run_callbacks'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sources.rb:349:in `did_change'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in `instance_exec'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in `block in execute'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in `execute'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sources/source_watcher.rb:279:in `update'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sources/source_watcher.rb:243:in `on_listener_change'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'

 -- /Library/Ruby/Gems/2.3.0/gems/listen-3.0.8/lib/listen/event/config.rb:23:in `call'

 -- /Library/Ruby/Gems/2.3.0/gems/listen-3.0.8/lib/listen/event/processor.rb:115:in `_process_changes'

 -- /Library/Ruby/Gems/2.3.0/gems/listen-3.0.8/lib/listen/event/processor.rb:19:in `block in loop_for'

 -- /Library/Ruby/Gems/2.3.0/gems/listen-3.0.8/lib/listen/event/processor.rb:15:in `loop'

 -- /Library/Ruby/Gems/2.3.0/gems/listen-3.0.8/lib/listen/event/processor.rb:15:in `loop_for'

 -- /Library/Ruby/Gems/2.3.0/gems/listen-3.0.8/lib/listen/event/loop.rb:84:in `_wait_for_changes'

 -- /Library/Ruby/Gems/2.3.0/gems/listen-3.0.8/lib/listen/event/loop.rb:42:in `block in setup'
```

The webserver is started and the website is rendered, but the `watch` is not executed, which means the website is not automatically rebuilding after a change. Only restarting `bundle exec bookbinder watch` leads to a rebuild of the website. 

Any idea, what might be wrong?

**Comment by ramkumarvs** [comment]
@jhiemer were you able to fix this issue?.

**Comment by jhiemer** [comment]
@ramkumarvs nope still the same error unfortunately.

**Comment by ramkumarvs** [comment]
> @ramkumarvs nope still the same error unfortunately.
@jhiemer thanks

**Comment by amiramm** [comment]
@jknostman3 I'm having the same issue with bookbinder.

```bundle exec bookbinder watch
  copying /Users/amirammizne/sandbox/docs-redislabs-enterprise/docs-layout
Gathering docs-content
  copying /Users/amirammizne/sandbox/docs-redislabs-enterprise/docs-content

Running middleman...

== The Middleman is loading
== LiveReload accepting connections from ws://172.16.0.120:35729
E, [2019-05-24T11:56:11.035912 #45680] ERROR -- : exception while processing events: Is a directory @ io_fread - /Users/amirammizne/sandbox/docs-redislabs-enterprise/docs-book/output/master_middleman/source/redis-labs-enterprise Backtrace:

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util/binary.rb:70:in `read'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util/binary.rb:70:in `file_contents_include_binary_bytes?'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util/binary.rb:38:in `binary?'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/resource.rb:175:in `binary?'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/core_extensions/front_matter.rb:37:in `block in manipulate_resource_list'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/core_extensions/front_matter.rb:36:in `each'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/core_extensions/front_matter.rb:36:in `manipulate_resource_list'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:234:in `block (4 levels) in ensure_resource_list_updated!'

 -- /Library/Ruby/Gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:232:in `block (3 levels) in ensure_resource_list_updated!'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:231:in `block (2 levels) in ensure_resource_list_updated!'

 -- /Library/Ruby/Gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:224:in `block in ensure_resource_list_updated!'

 -- /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:221:in `ensure_resource_list_updated!'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/extensions/on_disk.rb:51:in `update_files'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sources.rb:366:in `block in run_callbacks'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sources.rb:359:in `run_callbacks'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sources.rb:349:in `did_change'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in `instance_exec'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in `block in execute'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'

 -- /Library/Ruby/Gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in `execute'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sources/source_watcher.rb:279:in `update'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'

 -- /Library/Ruby/Gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sources/source_watcher.rb:243:in `on_listener_change'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'

 -- /Library/Ruby/Gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'

 -- /Library/Ruby/Gems/2.3.0/gems/listen-3.0.8/lib/listen/event/config.rb:23:in `call'

 -- /Library/Ruby/Gems/2.3.0/gems/listen-3.0.8/lib/listen/event/processor.rb:115:in `_process_changes'

 -- /Library/Ruby/Gems/2.3.0/gems/listen-3.0.8/lib/listen/event/processor.rb:19:in `block in loop_for'

 -- /Library/Ruby/Gems/2.3.0/gems/listen-3.0.8/lib/listen/event/processor.rb:15:in `loop'

 -- /Library/Ruby/Gems/2.3.0/gems/listen-3.0.8/lib/listen/event/processor.rb:15:in `loop_for'

 -- /Library/Ruby/Gems/2.3.0/gems/listen-3.0.8/lib/listen/event/loop.rb:84:in `_wait_for_changes'

 -- /Library/Ruby/Gems/2.3.0/gems/listen-3.0.8/lib/listen/event/loop.rb:42:in `block in setup'

 -- /Library/Ruby/Gems/2.3.0/gems/listen-3.0.8/lib/listen/internals/thread_pool.rb:6:in `block in add'

== View your site at "http://localhost:4567", "http://127.0.0.1:4567"
== Inspect your site configuration at "http://localhost:4567/__middleman", "http://127.0.0.1:4567/__middleman"```

Webserver is running but 'watch' isn't updating changes.

**Comment by jknostman3** [comment]
@amiramm if you end the watch with Control C and start it again does it show the changes you made?

**Comment by amiramm** [comment]
Yes, it does. This is what I've been doing.

**Comment by jknostman3** [comment]
@amiramm Unfortunately with the older versions of the partner template that were in the repo's for your first two tiles on PivNet that is the only workaround that I have found to work. It should auto-update the watch with the Tile Manager tile docs since that is from a newer partner template.
